// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Uygulama ilk açıldığında Rust loglarını Android sistemine bağlar.
Future<void> initLogger() => RustLib.instance.api.crateApiSimpleInitLogger();

/// SIP çağrısını başlatır ve olayları Flutter UI'a anlık olarak stream eder.
Stream<String> startSipCall({
  required String targetIp,
  required int targetPort,
  required String toUser,
  required String fromUser,
}) => RustLib.instance.api.crateApiSimpleStartSipCall(
  targetIp: targetIp,
  targetPort: targetPort,
  toUser: toUser,
  fromUser: fromUser,
);
